import type { TutorialStepConfig, TutorialErrorConfig, TutorialStepId, TutorialErrorType } from '../types/game';

export const GAME_CONFIG = {
  MAP_WIDTH: 800,
  MAP_HEIGHT: 1200,
  PLAYER: {
    MOVE_SPEED: 120,
    MOVE_LERP: 0.12,
    AUTO_DESCENT_SPEED: 18,
    HORIZONTAL_LERP: 0.08,
  },
  SONAR: {
    MAX_RADIUS: 500,
    SPEED: 280,
    MAX_CHARGES: 5,
    RECHARGE_TIME: 3000,
    COLOR: 0x00ffaa,
  },
  TARGETS: {
    CREATURE_COUNT: 6,
    WRECK_COUNT: 3,
    DANGER_COUNT: 4,
    MIN_RADIUS: 18,
    MAX_RADIUS: 45,
    SPAWN_MARGIN: 60,
  },
  SCORE: {
    CREATURE_POINTS: 100,
    WRECK_POINTS: 200,
    DANGER_PENALTY: -150,
    LIFE_LOST: 1,
    BONUS_PER_LEVEL: 50,
  },
  GAME: {
    INITIAL_LIVES: 3,
    TARGETS_PER_LEVEL: 8,
  },
  TUTORIAL: {
    ENABLED: true,
    NEWBIE_MAX_LEVELS: 2,
    DANGER_REDUCTION: {
      LEVEL_1_DANGER_RATIO: 0.4,
      LEVEL_2_DANGER_RATIO: 0.7,
      LEVEL_1_MIN_DANGER: 1,
      LEVEL_2_MIN_DANGER: 2,
      LEVEL_1_MAX_DANGER: 2,
      LEVEL_2_MAX_DANGER: 3,
    },
    LIVES_BONUS: {
      LEVEL_1_BONUS: 1,
      LEVEL_2_BONUS: 0,
    },
    SONAR_BONUS: {
      LEVEL_1_BONUS: 2,
      LEVEL_2_BONUS: 1,
    },
    DAMAGE_REDUCTION: {
      LEVEL_1_DANGER_PENALTY_RATIO: 0.5,
      LEVEL_2_DANGER_PENALTY_RATIO: 0.8,
      LEVEL_1_LIFE_PENALTY_RATIO: 0.5,
      LEVEL_2_LIFE_PENALTY_RATIO: 0.8,
    },
  },
  COMBO: {
    COMBO_TIMEOUT: 8000,
    SONAR_COMBO_TIMEOUT: 5000,
    MULTIPLIERS: [
      { combo: 3, multiplier: 1.2 },
      { combo: 5, multiplier: 1.5 },
      { combo: 8, multiplier: 2.0 },
      { combo: 12, multiplier: 2.5 },
      { combo: 16, multiplier: 3.0 },
      { combo: 20, multiplier: 4.0 },
    ],
    SONAR_MULTIPLIERS: [
      { combo: 2, multiplier: 1.1 },
      { combo: 4, multiplier: 1.2 },
      { combo: 6, multiplier: 1.3 },
      { combo: 8, multiplier: 1.5 },
    ],
    MILESTONE_BONUSES: [
      { combo: 5, points: 100, charges: 1 },
      { combo: 10, points: 200, charges: 1 },
      { combo: 15, points: 300, charges: 2 },
      { combo: 20, points: 500, charges: 2 },
      { combo: 25, points: 800, charges: 3 },
      { combo: 30, points: 1000, charges: 3 },
    ],
    SONAR_MILESTONE_BONUSES: [
      { combo: 3, points: 50, charges: 0 },
      { combo: 5, points: 100, charges: 1 },
      { combo: 8, points: 150, charges: 1 },
      { combo: 10, points: 200, charges: 2 },
    ],
    WRECK_BONUS_MULTIPLIER: 1.5,
    CREATURE_BONUS_MULTIPLIER: 1.0,
  },
  DEPTH: {
    ZONES: [
      { name: '浅层', maxDepth: 300, pressureDrain: 0, wreckValueBonus: 1.0, highValueWreckChance: 0.1 },
      { name: '中层', maxDepth: 600, pressureDrain: 0.3, wreckValueBonus: 1.3, highValueWreckChance: 0.25 },
      { name: '深层', maxDepth: 900, pressureDrain: 0.8, wreckValueBonus: 1.8, highValueWreckChance: 0.45 },
      { name: '深渊', maxDepth: 1200, pressureDrain: 1.5, wreckValueBonus: 2.5, highValueWreckChance: 0.65 },
    ],
    MAX_PRESSURE_INTEGRITY: 100,
    PRESSURE_WARNING_THRESHOLD: 30,
    PRESSURE_CRITICAL_THRESHOLD: 15,
    PRESSURE_DAMAGE_INTERVAL: 2.0,
    PRESSURE_DAMAGE_PER_INTERVAL: 1,
    PRESSURE_REGEN_RATE: 0.5,
    DEPTH_SCORE_BONUS_PER_ZONE: 0.15,
  },
  COLORS: {
    BACKGROUND: 0x000814,
    GRID: 0x003344,
    SONAR: 0x00ffaa,
    CREATURE: 0x00e5ff,
    WRECK: 0xffcc00,
    DANGER: 0xff3355,
    PLAYER: 0x00ff88,
    COMBO: {
      LOW: 0x00ffaa,
      MEDIUM: 0xffcc00,
      HIGH: 0xff8800,
      EXTREME: 0xff3355,
      LEGENDARY: 0xff00ff,
    },
  },
  LEGENDARY_CHAIN: {
    SPAWN_CHANCE: 0.12,
    RARE_SPAWN_CHANCE: 0.25,
    MIN_LEVEL_FOR_SPAWN: 2,
    TIMER_DURATION: 15,
    TIMER_WARNING_THRESHOLD: 5,
    POINTS_MULTIPLIER: 3.0,
    RARE_POINTS_MULTIPLIER: 1.8,
    CHAIN_LENGTHS: [
      { chainLength: 2, bonusPoints: 300, bonusLives: 0, bonusSonarCharges: 1, achievementName: '传说初现', achievementDescription: '连续收集2个传说目标' },
      { chainLength: 3, bonusPoints: 800, bonusLives: 1, bonusSonarCharges: 2, achievementName: '深渊回响', achievementDescription: '连续收集3个传说目标' },
      { chainLength: 5, bonusPoints: 2000, bonusLives: 2, bonusSonarCharges: 3, achievementName: '传说猎手', achievementDescription: '连续收集5个传说目标' },
      { chainLength: 8, bonusPoints: 5000, bonusLives: 3, bonusSonarCharges: 5, achievementName: '神话追寻者', achievementDescription: '连续收集8个传说目标' },
    ],
    SPECIAL_ECHO_COLOR: 0xffaa00,
    SPECIAL_ECHO_SIZE_MUL: 1.8,
    SPECIAL_ECHO_LIFE_MUL: 1.5,
    SPECIAL_ECHO_COUNT: 5,
    LEGENDARY_NAMES: {
      creature: ['远古利维坦', '幽灵鲸', '水晶龙鱼', '深渊凤凰', '永恒海星', '星辉水母王'],
      wreck: ['亚特兰蒂斯碎片', '远古神殿遗迹', '龙骨宝船', '深渊王冠', '时间封印之箱', '失落的神器'],
    },
  },
};

export const CREATURE_NAMES = [
  '深海灯笼鱼',
  '巨型章鱼',
  '透明水母',
  '深海剑鱼',
  '发光乌贼',
  '珊瑚虫群',
  '海天使',
  '吞噬鳗',
];

export const WRECK_NAMES = [
  '古代沉船',
  '飞机残骸',
  '海底遗迹',
  '废弃潜艇',
  '货物集装箱',
];

export const DANGER_NAMES = [
  '危险水雷',
  '深海漩涡',
  '毒刺水母群',
  '海底火山口',
  '高压电流区',
];

export const RESCUE_CONFIG = {
  MAP_WIDTH: 800,
  MAP_HEIGHT: 1200,
  GAME: {
    BASE_TIME: 180,
    TIME_PER_LEVEL: 30,
    MAX_FALSE_REPORTS: 3,
    FALSE_REPORT_PENALTY: -150,
    LEVELS: [
      { realCapsules: 2, decoys: 1, interferenceZones: 2, timeBonus: 0 },
      { realCapsules: 3, decoys: 2, interferenceZones: 3, timeBonus: 30 },
      { realCapsules: 4, decoys: 3, interferenceZones: 4, timeBonus: 60 },
      { realCapsules: 5, decoys: 4, interferenceZones: 5, timeBonus: 90 },
      { realCapsules: 6, decoys: 5, interferenceZones: 6, timeBonus: 120 },
    ],
  },
  SONAR: {
    MAX_RADIUS: 450,
    SPEED: 240,
    MAX_CHARGES: 4,
    RECHARGE_TIME: 4000,
    COLOR: 0x00ccff,
    INTERFERENCE_ATTENUATION: 0.6,
  },
  SCORE: {
    DETECT_BONUS: 50,
    CONFIRM_BONUS: 200,
    RESCUE_BONUS: 500,
    TIME_BONUS_PER_SEC: 5,
    ACCURACY_BONUS: 300,
    PERFECT_RESCUE_BONUS: 1000,
    CAPSULE_MIN_RADIUS: 22,
    CAPSULE_MAX_RADIUS: 40,
  },
  CAPSULE: {
    REAL_NAMES: [
      '深海科研舱',
      '观光潜水艇',
      '海底工作站',
      '深海采矿舱',
      '科考探测舱',
      '救援中继站',
      '深海观测站',
      '海底实验室',
    ],
    DECOY_NAMES: [
      '废弃集装箱',
      '沉船碎片',
      '大型岩块',
      '海底残骸',
      '废弃浮标',
      '金属沉积物',
    ],
  },
  INTERFERENCE: {
    NOISE_NAMES: ['噪声干扰区', '信号盲区', '磁异常带'],
    DECOY_ZONE_NAMES: ['假信号源', '镜像区域', '回声陷阱'],
    BLOCKER_NAMES: ['海底山脉', '熔岩带', '冰层覆盖区'],
    MIN_RADIUS: 80,
    MAX_RADIUS: 180,
  },
  PATH: {
    MAX_ALLOWED_DEVIATION: 60,
    WARNING_DEVIATION: 40,
    MAX_YAW_WARNINGS: 3,
    PLAYER_SPEED: 120,
    PATH_NODE_RADIUS: 15,
    HIGH_RISK_THRESHOLD: 0.7,
    OFFTRACK_TIME_PENALTY: 5,
    OFFTRACK_SCORE_PENALTY: -80,
    HIGHRISK_TIME_PENALTY: 8,
    HIGHRISK_SCORE_PENALTY: -120,
    BLOCKER_TIME_PENALTY: 15,
    BLOCKER_SCORE_PENALTY: -200,
    PATH_PROGRESS_BONUS_PER_100PX: 20,
    SAFE_PATH_BONUS: 200,
    PERFECT_PATH_BONUS: 500,
    RETURN_TO_PATH_BONUS: 50,
  },
  COLORS: {
    BACKGROUND: 0x000a1a,
    GRID: 0x002244,
    SONAR: 0x00ccff,
    REAL_CAPSULE: 0x00ff88,
    DECOY_CAPSULE: 0xff8844,
    CONFIRMED_CAPSULE: 0x00ffcc,
    RESCUED_CAPSULE: 0x00ffff,
    INTERFERENCE_NOISE: 0x6644aa,
    INTERFERENCE_DECOY: 0xaa6644,
    INTERFERENCE_BLOCKER: 0x444466,
    PLAYER: 0x44ffaa,
    WARNING: 0xff6644,
    DANGER: 0xff3355,
    PATH_SAFE: 0x00ff88,
    PATH_CAUTION: 0xffcc00,
    PATH_DANGER: 0xff6644,
    PATH_HIGH_RISK: 0xff0033,
    PATH_BLOCKED: 0x660033,
    PATH_OFFTRACK: 0xff0000,
  },
};

export const TUTORIAL_STEPS: TutorialStepConfig[] = [
  {
    id: 'welcome',
    title: '欢迎来到深海探测',
    description: '你将作为一名深海探测员，使用声呐系统探索神秘的深海世界。让我们一起学习基本操作吧！',
    icon: '🌊',
    duration: 4000,
    autoAdvance: true,
    highlightLevel: 'soft',
    skipable: true,
    nextStepDelay: 500,
  },
  {
    id: 'sonar_intro',
    title: '认识声呐系统',
    description: '声呐是你探索深海的核心工具。点击地图任意位置释放声呐波，它会帮助你发现隐藏在深海中的目标。注意下方的声呐能量条！',
    icon: '📡',
    duration: 5000,
    autoAdvance: true,
    highlightElement: 'sonar_bar',
    highlightLevel: 'pulse',
    skipable: true,
    nextStepDelay: 300,
  },
  {
    id: 'sonar_fire',
    title: '释放你的第一次声呐',
    description: '现在试试看！点击地图上的任意位置释放声呐波，观察声呐如何扩散并照亮隐藏的目标。',
    icon: '👆',
    duration: 0,
    autoAdvance: false,
    requiredAction: 'sonar_fire',
    actionCountRequired: 1,
    highlightLevel: 'pulse',
    skipable: false,
  },
  {
    id: 'discover_target',
    title: '发现隐藏目标',
    description: '太棒了！声呐波已经帮助你发现了深海中的目标。你可以看到不同颜色的点——蓝色代表海洋生物，金色代表残骸遗迹。继续释放声呐发现更多目标！',
    icon: '✨',
    duration: 0,
    autoAdvance: false,
    requiredAction: 'target_discover',
    actionCountRequired: 2,
    highlightElement: 'progress_bar',
    highlightLevel: 'soft',
    skipable: true,
  },
  {
    id: 'collect_intro',
    title: '收集已发现的目标',
    description: '发现目标后，点击目标即可收集它们！海洋生物（蓝色）和残骸遗迹（金色）都能获得分数。',
    icon: '🎯',
    duration: 4500,
    autoAdvance: true,
    highlightLevel: 'soft',
    skipable: true,
    nextStepDelay: 300,
  },
  {
    id: 'collect_creature',
    title: '收集海洋生物',
    description: '现在去点击一个蓝色的海洋生物来收集它吧！你可以在左上角看到你的分数增长。',
    icon: '🐟',
    duration: 0,
    autoAdvance: false,
    requiredAction: 'collect_creature',
    actionCountRequired: 1,
    highlightElement: 'score_panel',
    highlightLevel: 'pulse',
    skipable: false,
  },
  {
    id: 'danger_warning',
    title: '注意危险目标',
    description: '⚠️ 深海中也潜伏着危险！红色的目标是危险物，触碰它们会损失生命值和分数。请小心避开红色目标！',
    icon: '⚠️',
    duration: 6000,
    autoAdvance: true,
    highlightElement: 'lives_panel',
    highlightLevel: 'strong',
    skipable: true,
    nextStepDelay: 500,
  },
  {
    id: 'wreck_intro',
    title: '探索残骸遗迹',
    description: '金色的残骸遗迹通常拥有更高的分数奖励。在浅层海域比较安全，但越往深处，宝物越珍贵，危险也越多！',
    icon: '🏴‍☠️',
    duration: 4000,
    autoAdvance: true,
    highlightLevel: 'soft',
    skipable: true,
    nextStepDelay: 300,
  },
  {
    id: 'combo_intro',
    title: '连击系统',
    description: '连续收集目标可以触发连击，获得分数加成！注意如果触碰危险或者长时间不收集，连击就会中断。',
    icon: '🔥',
    duration: 4500,
    autoAdvance: true,
    highlightLevel: 'soft',
    skipable: true,
    nextStepDelay: 300,
  },
  {
    id: 'depth_intro',
    title: '深度与压力系统',
    description: '你的潜艇会自动下潜。越深的海域宝物越多，但耐压值也会下降。耐压值降到临界值时会持续损失生命！注意顶部的深度面板。',
    icon: '⬇️',
    duration: 5000,
    autoAdvance: true,
    highlightElement: 'depth_panel',
    highlightLevel: 'strong',
    skipable: true,
    nextStepDelay: 300,
  },
  {
    id: 'level_progression',
    title: '关卡进阶',
    description: '收集足够的目标就能升级进入下一关！升级会奖励额外的声呐能量和分数。难度也会逐步提升，你准备好了吗？',
    icon: '⬆️',
    duration: 4000,
    autoAdvance: true,
    highlightLevel: 'soft',
    skipable: true,
    nextStepDelay: 500,
  },
  {
    id: 'tutorial_complete',
    title: '教程完成！',
    description: '你已经掌握了所有基本操作！现在自由探索深海世界吧。前两关危险较少，好好利用这段时间熟悉操作~',
    icon: '🎉',
    duration: 5000,
    autoAdvance: true,
    highlightLevel: 'pulse',
    skipable: true,
  },
];

export const TUTORIAL_ERROR_HINTS: Partial<Record<TutorialErrorType, TutorialErrorConfig>> = {
  tap_undiscovered: {
    type: 'tap_undiscovered',
    title: '目标尚未发现',
    message: '你点击了一个未被发现的区域，这里可能什么都没有哦~',
    suggestion: '先释放声呐波来发现隐藏的目标，然后再点击收集！',
    icon: '🔍',
    severity: 'info',
    duration: 3000,
    repeatThreshold: 2,
  },
  tap_danger: {
    type: 'tap_danger',
    title: '危险警告！',
    message: '你刚才点击了危险目标！',
    suggestion: '红色目标是危险物，触碰会损失生命值和分数。请收集蓝色和金色的目标！',
    icon: '🚨',
    severity: 'error',
    duration: 4500,
    repeatThreshold: 1,
  },
  HIT_DANGER: {
    type: 'HIT_DANGER',
    title: '危险警告！',
    message: '你刚才点击了危险目标！',
    suggestion: '红色目标是危险物，触碰会损失生命值和分数。请收集蓝色和金色的目标！',
    icon: '🚨',
    severity: 'error',
    duration: 4500,
    repeatThreshold: 1,
  },
  sonar_no_charges: {
    type: 'sonar_no_charges',
    title: '声呐能量不足',
    message: '你的声呐能量用完了！',
    suggestion: '耐心等待声呐能量自动恢复，或者收集更多目标等待升级奖励！',
    icon: '🔋',
    severity: 'warning',
    duration: 3500,
    repeatThreshold: 1,
  },
  NO_SONAR_CHARGE: {
    type: 'NO_SONAR_CHARGE',
    title: '声呐能量不足',
    message: '你的声呐能量用完了！',
    suggestion: '耐心等待声呐能量自动恢复，或者收集更多目标等待升级奖励！',
    icon: '🔋',
    severity: 'warning',
    duration: 3500,
    repeatThreshold: 1,
  },
  sonar_miss: {
    type: 'sonar_miss',
    title: '声呐未发现目标',
    message: '这次声呐没有发现任何东西...',
    suggestion: '尝试向不同的位置释放声呐，特别是地图中还未探索的区域！',
    icon: '💨',
    severity: 'info',
    duration: 2500,
    repeatThreshold: 3,
  },
  danger_collision: {
    type: 'danger_collision',
    title: '生命损失！',
    message: '你触碰了危险目标，损失了生命值。',
    suggestion: '仔细识别颜色：蓝色=生物（安全），金色=残骸（安全），红色=危险（避开）！',
    icon: '💔',
    severity: 'error',
    duration: 5000,
    repeatThreshold: 1,
  },
  depth_pressure_critical: {
    type: 'depth_pressure_critical',
    title: '耐压值危险！',
    message: '你的耐压值已经降到警戒线以下！',
    suggestion: '尽快收集目标升级，或尽量避免长时间停留在深海区域！',
    icon: '🌡️',
    severity: 'warning',
    duration: 4000,
    repeatThreshold: 1,
  },
  combo_broken_early: {
    type: 'combo_broken_early',
    title: '连击中断',
    message: '你的连击中断了！',
    suggestion: '连续收集目标可以保持连击并获得分数加成，注意不要触碰危险！',
    icon: '💢',
    severity: 'info',
    duration: 2500,
    repeatThreshold: 2,
  },
};
